[toolchain]
anchor_version = "1.0.2"
solana_version = "3.1.7"

[features]
resolution = true
skip-lint = false

[programs.localnet]
reservepay = "ERFq8y9tC4bjMk4AbLoM7zZXtvRcxsHdCMa9GpSnwxsU"

[programs.devnet]
reservepay = "ERFq8y9tC4bjMk4AbLoM7zZXtvRcxsHdCMa9GpSnwxsU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun run --bun mocha -t 1000000 tests/**/*.ts"
